// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:cinema_city/data/models/filters/event_type_filter.dart';
import 'package:cinema_city/data/models/filters/genre_filter.dart';
import 'package:cinema_city/data/models/filters/score_filter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EventTypeFilterAdapter());
    registerAdapter(GenreFilterAdapter());
    registerAdapter(ScoreFilterAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EventTypeFilterAdapter());
    registerAdapter(GenreFilterAdapter());
    registerAdapter(ScoreFilterAdapter());
  }
}
